### ISSUE TITLE
Integrate into Task Runner Explorer

### ISSUE THREAD

**Issue by timschoch** [mwiedemeyer/SPDeployer#2]
We use Grunt Tasks in the Task Runner for compiling and minifying our sass and js stuff and it would be nice if the deployment could be used as a step there too. Any chance you could make this happen?

**Comment by mwiedemeyer** [comment]
Hi,
I've just uploaded [SPDeployment](https://github.com/mwiedemeyer/SPDeployment) which is a command line tool to deploy to SharePoint. You can install it with `npm install spdeployment -g`.

Currently there is no explicit grunt or gulp task, but you can use a process runner task to execute it.

That means, that this VS extension will not be updated to be included in task runner, because it is mainly for rapid developing/testing changed files.
